---
language: python
dist: xenial
python:
- "2.7"
- "3.7"
install:
- pip install .
script:
- sweepj2 --template example/script.j2 --space example/space.yml --make-executable
- test 31 -eq $(ls -l ./sweepj2-output/ | wc -l)
- cat ./sweepj2-output/008-20-0.5-3 | grep 'wordNgrams 3'
- cat ./sweepj2-output/008-20-0.5-3 | grep 'epoch 20'
- cat ./sweepj2-output/008-20-0.5-3 | grep 'lr 0.5'
- cat ./sweepj2-output/030-30-0.8-5 | grep 'wordNgrams 5'
- cat ./sweepj2-output/030-30-0.8-5 | grep 'epoch 30'
- cat ./sweepj2-output/030-30-0.8-5 | grep 'lr 0.8'
